package vehicleinventory;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.*;

public class DashBoardFrame extends javax.swing.JFrame {

    ArrayList<Vehicle> vl = new ArrayList<>();
    ArrayList<Vehicle> vl2 = new ArrayList<>();
    DefaultTableModel dtm;
    DefaultTableModel dtm2;

    public DashBoardFrame() {
        initComponents();
        loadCarDataFromFile();
        loadBikeDataFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        homebutton = new javax.swing.JButton();
        carbutton = new javax.swing.JButton();
        bikeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        regNoBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        brandBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        modelBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        colorBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        status1 = new javax.swing.JRadioButton();
        status2 = new javax.swing.JRadioButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        conditionBox = new javax.swing.JComboBox<>();
        domBox = new com.toedter.calendar.JDateChooser();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CarDataTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        regNoBox1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        brandBox1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        modelBox1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        colorBox1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        status3 = new javax.swing.JRadioButton();
        status4 = new javax.swing.JRadioButton();
        addButton1 = new javax.swing.JButton();
        updateButton1 = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();
        exitButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        conditionBox1 = new javax.swing.JComboBox<>();
        domBox1 = new com.toedter.calendar.JDateChooser();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CarDataTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        ccBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 750));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel2.setBackground(new java.awt.Color(124, 0, 227));

        jButton1.setBackground(new java.awt.Color(124, 0, 227));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        homebutton.setBackground(new java.awt.Color(124, 0, 227));
        homebutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        homebutton.setForeground(new java.awt.Color(255, 255, 255));
        homebutton.setText("HOME");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });

        carbutton.setBackground(new java.awt.Color(124, 0, 227));
        carbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        carbutton.setForeground(new java.awt.Color(255, 255, 255));
        carbutton.setText("CAR");
        carbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carbuttonActionPerformed(evt);
            }
        });

        bikeButton.setBackground(new java.awt.Color(124, 0, 227));
        bikeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bikeButton.setForeground(new java.awt.Color(255, 255, 255));
        bikeButton.setText("BIKE");
        bikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bikeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bikeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(homebutton)
                .addGap(18, 18, 18)
                .addComponent(carbutton)
                .addGap(18, 18, 18)
                .addComponent(bikeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(124, 0, 227));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MANAGEMENT SYSTEM.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(124, 0, 227));
        jLabel3.setText("WELLCOME TO INVENTORY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, "card2");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(124, 0, 227));
        jLabel5.setText("REG NO");

        regNoBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(124, 0, 227));
        jLabel6.setText("BRAND");

        brandBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(124, 0, 227));
        jLabel7.setText("MODEL");

        modelBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(124, 0, 227));
        jLabel8.setText("COLOR");

        colorBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(124, 0, 227));
        jLabel9.setText("STATUS");

        status1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(status1);
        status1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        status1.setForeground(new java.awt.Color(124, 0, 227));
        status1.setText("RENTED");
        status1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status1ActionPerformed(evt);
            }
        });

        status2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(status2);
        status2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        status2.setForeground(new java.awt.Color(124, 0, 227));
        status2.setText("AVAILABLE");
        status2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status2ActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(124, 0, 227));
        addButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(124, 0, 227));
        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(124, 0, 227));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(124, 0, 227));
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(124, 0, 227));
        jLabel10.setText("DATE OF");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(124, 0, 227));
        jLabel11.setText("MANUFACTURE");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(124, 0, 227));
        jLabel12.setText("CONDITION");

        conditionBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        conditionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "New", "Like New", "Old", "Too Old" }));

        CarDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REG NO", "BRAND", "MODEL", "COLOR", "STATUS", "DATE OF MANUFACTURE", "CONDITION"
            }
        ));
        CarDataTable.setGridColor(new java.awt.Color(124, 0, 227));
        CarDataTable.setSelectionBackground(new java.awt.Color(124, 0, 227));
        CarDataTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        CarDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarDataTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CarDataTable);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(domBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regNoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandBox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(status1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(status2))
                                .addComponent(colorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(conditionBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regNoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status1)
                            .addComponent(status2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addComponent(domBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(conditionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5, "card3");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(124, 0, 227));
        jLabel13.setText("REG NO");

        regNoBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(124, 0, 227));
        jLabel14.setText("BRAND");

        brandBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(124, 0, 227));
        jLabel15.setText("MODEL");

        modelBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(124, 0, 227));
        jLabel16.setText("COLOR");

        colorBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(124, 0, 227));
        jLabel17.setText("STATUS");

        status3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(status3);
        status3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        status3.setForeground(new java.awt.Color(124, 0, 227));
        status3.setText("RENTED");
        status3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status3ActionPerformed(evt);
            }
        });

        status4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(status4);
        status4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        status4.setForeground(new java.awt.Color(124, 0, 227));
        status4.setText("AVAILABLE");
        status4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status4ActionPerformed(evt);
            }
        });

        addButton1.setBackground(new java.awt.Color(124, 0, 227));
        addButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addButton1.setForeground(new java.awt.Color(255, 255, 255));
        addButton1.setText("ADD");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        updateButton1.setBackground(new java.awt.Color(124, 0, 227));
        updateButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updateButton1.setForeground(new java.awt.Color(255, 255, 255));
        updateButton1.setText("UPDATE");
        updateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton1ActionPerformed(evt);
            }
        });

        deleteButton1.setBackground(new java.awt.Color(124, 0, 227));
        deleteButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deleteButton1.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton1.setText("DELETE");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });

        exitButton1.setBackground(new java.awt.Color(124, 0, 227));
        exitButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitButton1.setForeground(new java.awt.Color(255, 255, 255));
        exitButton1.setText("EXIT");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(124, 0, 227));
        jLabel18.setText("DATE OF");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(124, 0, 227));
        jLabel19.setText("MANUFACTURE");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(124, 0, 227));
        jLabel20.setText("CONDITION");

        conditionBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        conditionBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "New", "Like New", "Old", "Too Old" }));

        CarDataTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REG NO", "BRAND", "MODEL", "COLOR", "STATUS", "DATE OF MANUFACTURE", "CONDITION", "CC"
            }
        ));
        CarDataTable1.setGridColor(new java.awt.Color(124, 0, 227));
        CarDataTable1.setSelectionBackground(new java.awt.Color(124, 0, 227));
        CarDataTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        CarDataTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarDataTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(CarDataTable1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(124, 0, 227));
        jLabel21.setText("CC");

        ccBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ccBox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(domBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regNoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(status3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(status4))
                                .addComponent(colorBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(conditionBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regNoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status3)
                    .addComponent(status4))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addComponent(domBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conditionBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel6, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarDataTableMouseClicked

        try {

            int i = CarDataTable.getSelectedRow();
            String a = dtm.getValueAt(i, 0).toString();
            String b = dtm.getValueAt(i, 1).toString();
            String c = dtm.getValueAt(i, 2).toString();
            String d = dtm.getValueAt(i, 3).toString();
            String e = dtm.getValueAt(i, 4).toString();
            String f = dtm.getValueAt(i, 5).toString();
            String g = dtm.getValueAt(i, 6).toString();

            regNoBox.setText(a);
            brandBox.setText(b);
            modelBox.setText(c);
            colorBox.setText(d);
            if (e.equalsIgnoreCase("Rented")) {
                status1.setSelected(true);
            } else {
                status2.setSelected(true);
            }
            Date D = new SimpleDateFormat("MMM d, y").parse((String) f.toString());
            domBox.setDate(D);
            conditionBox.setSelectedItem(g);
        }
        catch (Exception e) {
            System.out.println("" + e);
        }
    }//GEN-LAST:event_CarDataTableMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        dtm = (DefaultTableModel) CarDataTable.getModel();
        if (CarDataTable.getSelectedRowCount() == 1) {
            int i = CarDataTable.getSelectedRow();
            int p = JOptionPane.showConfirmDialog(this, "Do you want to delete?", "Delete", JOptionPane.YES_NO_OPTION, 3);

            if (p == 0) {
                dtm.removeRow(i);
                vl.remove(i);

                conditionBox.setSelectedIndex(0);
                regNoBox.setText("");
                brandBox.setText("");
                modelBox.setText("");
                colorBox.setText("");
                buttonGroup1.clearSelection();
                domBox.setCalendar(null);

                try {
                    saveTableDataToTextFile();
                } catch (IOException e) {
                    System.out.println("Error saving data to file: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Thanks");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a single row to delete.");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        dtm = (DefaultTableModel) CarDataTable.getModel();
        String condition = conditionBox.getSelectedItem().toString();
        String regNo = regNoBox.getText();
        String brand = brandBox.getText();
        String model = modelBox.getText();
        String color = colorBox.getText();
        String status = null, dom;
        dom = ((JTextField) domBox.getDateEditor().getUiComponent()).getText();
        if (status1.isSelected()) {
            status = "Rented";
        }
        if (status2.isSelected()) {
            status = "Available";
        }

        int i = CarDataTable.getSelectedRow();
        Vehicle v = vl.get(i);
        if (v instanceof Car) {
            Car car = (Car) v;
            vl.get(i).regNo = regNo;

            car.setBrand(brand);
            car.setModel(model);
            vl.get(i).color = color;
            vl.get(i).status = status;
            car.setDom(dom);
            vl.get(i).condition = condition;
            dtm.setValueAt(regNo, i, 0);
            dtm.setValueAt(brand, i, 1);
            dtm.setValueAt(model, i, 2);
            dtm.setValueAt(color, i, 3);
            dtm.setValueAt(status, i, 4);
            dtm.setValueAt(dom, i, 5);
            dtm.setValueAt(condition, i, 6);
            try {
                saveTableDataToTextFile();
            } catch (IOException e) {
                System.out.println("" + e);
            } 
            conditionBox.setSelectedIndex(0);
                regNoBox.setText("");
                brandBox.setText("");
                modelBox.setText("");
                colorBox.setText("");
                buttonGroup1.clearSelection();
                domBox.setCalendar(null);
        } 
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        dtm = (DefaultTableModel) CarDataTable.getModel();
        String regNo = regNoBox.getText();
        String brand = brandBox.getText();
        String model = modelBox.getText();
        String color = colorBox.getText();
        String status = null;
        if (status1.isSelected()) {
            status = "Rented";
        }
        if (status2.isSelected()) {
            status = "Available";
        }
        String dom = ((JTextField) domBox.getDateEditor().getUiComponent()).getText();
        String condition = conditionBox.getSelectedItem().toString();
        if (regNo.isEmpty() || brand.isEmpty() || model.isEmpty() || color.isEmpty() || status == null || dom.isEmpty() || condition.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input all data");
            return;
        } else {
            vl.add(new Car(regNo, brand, model, color, status, dom, condition));
            dtm = (DefaultTableModel) CarDataTable.getModel();
            dtm.setRowCount(0);
            Object d[] = new Object[7];
            for (Vehicle v : vl) {
                if (v instanceof Car) {
                    Car car = (Car) v;
                    d[0] = car.getRegNo();
                    d[1] = car.getBrand();
                    d[2] = car.getModel();
                    d[3] = car.getColor();
                    d[4] = car.getStatus();
                    d[5] = car.getDom();
                    d[6] = car.getCondition();
                    dtm.addRow(d);
                }
            }
            try {
                saveTableDataToTextFile();
            } catch (IOException e) {
                System.out.println("" + e);
            }
            conditionBox.setSelectedIndex(0);
            regNoBox.setText("");
            brandBox.setText("");
            modelBox.setText("");
            colorBox.setText("");
            buttonGroup1.clearSelection();
            domBox.setCalendar(null);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void status2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status2ActionPerformed

    private void status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status1ActionPerformed

    private void bikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bikeButtonActionPerformed
        jPanel3.removeAll();
        jPanel3.add(jPanel6);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_bikeButtonActionPerformed

    private void carbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carbuttonActionPerformed
        jPanel3.removeAll();
        jPanel3.add(jPanel5);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_carbuttonActionPerformed

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        jPanel3.removeAll();
        jPanel3.add(jPanel4);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_homebuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        LogInFrame LF = new LogInFrame();
        LF.setLocationRelativeTo(null);
        LF.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void status3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status3ActionPerformed

    private void status4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status4ActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
         dtm2 = (DefaultTableModel) CarDataTable1.getModel();
        String regNo = regNoBox1.getText();
        String brand = brandBox1.getText();
        String model = modelBox1.getText();
        String color = colorBox1.getText();
        String status = null;
        if (status3.isSelected()) {
            status = "Rented";
        }
        if (status4.isSelected()) {
            status = "Available";
        }
        String dom = ((JTextField) domBox1.getDateEditor().getUiComponent()).getText();
        String condition = conditionBox1.getSelectedItem().toString();
        String cc = ccBox.getText();
        
        if (regNo.isEmpty() || brand.isEmpty() || model.isEmpty() || color.isEmpty() || status == null || dom.isEmpty() || condition.isEmpty() || cc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input all data");
            return;
        } else {
            vl2.add(new Bike(regNo, brand, model, color, status, dom, condition, cc));
            dtm2 = (DefaultTableModel) CarDataTable1.getModel();
            dtm2.setRowCount(0);

            Object x[] = new Object[8];

            for (Vehicle v : vl2) {
                if (v instanceof Bike) {
                    Bike bike = (Bike) v;
                    x[0] = bike.getRegNo();
                    x[1] = bike.getBrand();
                    x[2] = bike.getModel();
                    x[3] = bike.getColor();
                    x[4] = bike.getStatus();
                    x[5] = bike.getDom();
                    x[6] = bike.getCondition();
                    x[7] = bike.getCc();
                    dtm2.addRow(x);
                }
            }
            conditionBox1.setSelectedIndex(0);
            regNoBox1.setText("");
            brandBox1.setText("");
            modelBox1.setText("");
            colorBox1.setText("");
            buttonGroup2.clearSelection();
            domBox1.setCalendar(null);
            ccBox.setText("");
            try {
                saveTableDataToTextFile1();
            } catch (IOException e) {
                System.out.println("" + e);
            }
        }
    }//GEN-LAST:event_addButton1ActionPerformed

    private void updateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton1ActionPerformed
        dtm2 = (DefaultTableModel) CarDataTable1.getModel();
        String condition = conditionBox1.getSelectedItem().toString();
        String regNo = regNoBox1.getText();
        String brand = brandBox1.getText();
        String model = modelBox1.getText();
        String color = colorBox1.getText();
        String status = null, dom;
        dom = ((JTextField) domBox1.getDateEditor().getUiComponent()).getText();
        if (status3.isSelected()) {
            status = "Rented";
        }
        if (status4.isSelected()) {
            status = "Available";
        }
        String cc = ccBox.getText();
        
        int i = CarDataTable1.getSelectedRow();
        Vehicle v = vl2.get(i);
         if (v instanceof Bike) {
            Bike bike = (Bike) v;
            vl2.get(i).regNo = regNo;
            bike.setBrand(brand);
            bike.setModel(model);
            vl2.get(i).color = color;
            vl2.get(i).status = status;
            bike.setDom(dom);
            vl2.get(i).condition = condition;
            bike.setCc(cc);
            dtm2.setValueAt(regNo, i, 0);
            dtm2.setValueAt(brand, i, 1);
            dtm2.setValueAt(model, i, 2);
            dtm2.setValueAt(color, i, 3);
            dtm2.setValueAt(status, i, 4);
            dtm2.setValueAt(dom, i, 5);
            dtm2.setValueAt(condition, i, 6);
            dtm2.setValueAt(cc, i, 7);
            
            try {
                saveTableDataToTextFile1();
            } catch (IOException e) {
                System.out.println("" + e);
            }
            conditionBox1.setSelectedIndex(0);
            regNoBox1.setText("");
            brandBox1.setText("");
            modelBox1.setText("");
            colorBox1.setText("");
            buttonGroup2.clearSelection();
            domBox1.setCalendar(null);
            ccBox.setText("");
        }
        
        
    }//GEN-LAST:event_updateButton1ActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        dtm2 = (DefaultTableModel) CarDataTable1.getModel();
        if (CarDataTable1.getSelectedRowCount() == 1) {
            int i = CarDataTable1.getSelectedRow();
            int p = JOptionPane.showConfirmDialog(this, "Do you want to delete?", "Delete", JOptionPane.YES_NO_OPTION, 3);

            if (p == 0) {
                dtm2.removeRow(i);
                vl2.remove(i);

                conditionBox.setSelectedIndex(0);
                regNoBox.setText("");
                brandBox.setText("");
                modelBox.setText("");
                colorBox.setText("");
                buttonGroup1.clearSelection();
                domBox.setCalendar(null);
                ccBox.setText("");

                try {
                    saveTableDataToTextFile1();
                } catch (IOException e) {
                    System.out.println("Error saving data to file: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Thanks");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a single row to delete.");
        }
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void CarDataTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarDataTable1MouseClicked
        
        try {
            int i = CarDataTable1.getSelectedRow();
            String a = dtm2.getValueAt(i, 0).toString();
            String b = dtm2.getValueAt(i, 1).toString();
            String c = dtm2.getValueAt(i, 2).toString();
            String d = dtm2.getValueAt(i, 3).toString();
            String e = dtm2.getValueAt(i, 4).toString();
            String f = dtm2.getValueAt(i, 5).toString();
            String g = dtm2.getValueAt(i, 6).toString();
            String h = dtm2.getValueAt(i, 7).toString();

            regNoBox1.setText(a);
            brandBox1.setText(b);
            modelBox1.setText(c);
            colorBox1.setText(d);
            if (e.equalsIgnoreCase("Rented")) {
                status3.setSelected(true);
            } else {
                status4.setSelected(true);
            }
            Date D = new SimpleDateFormat("MMM d, y").parse((String) f.toString());
            domBox1.setDate(D);
            conditionBox1.setSelectedItem(g);
            ccBox.setText(h);
            
        }
        catch (Exception e) {
            System.out.println("" + e);
        }
    }//GEN-LAST:event_CarDataTable1MouseClicked


    private void loadCarDataFromFile() {
        String filePath = "carData.txt";
        dtm = (DefaultTableModel) CarDataTable.getModel();
        dtm.setRowCount(0);
        vl.clear();

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String currentLine;

            while ((currentLine = reader.readLine()) != null) {
                String[] data = currentLine.split(",, ");
                String regNo = data[0].split(": ")[1].trim();
                String brand = data[1].split(": ")[1].trim();
                String model = data[2].split(": ")[1].trim();
                String color = data[3].split(": ")[1].trim();
                String status = data[4].split(": ")[1].trim();
                String dom = data[5].split(": ")[1].trim();
                String condition = data[6].split(": ")[1].trim();
                Object[] rowData = {regNo, brand, model, color, status, dom, condition};
                dtm.addRow(rowData);

                Car car = new Car(regNo, brand, model, color, status, dom, condition);
                vl.add(car);
            }
        } catch (IOException e) {
            System.out.println("" + e);
        }
    }
    private void loadBikeDataFromFile() {
        String filePath = "bikeData.txt";
        dtm2 = (DefaultTableModel) CarDataTable1.getModel();
        dtm2.setRowCount(0);
        vl2.clear();

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String currentLine;

            while ((currentLine = reader.readLine()) != null) {
                String[] data = currentLine.split(",, ");
                String regNo = data[0].split(": ")[1].trim();
                String brand = data[1].split(": ")[1].trim();
                String model = data[2].split(": ")[1].trim();
                String color = data[3].split(": ")[1].trim();
                String status = data[4].split(": ")[1].trim();
                String dom = data[5].split(": ")[1].trim();
                String condition = data[6].split(": ")[1].trim();
                String cc = data[7].split(": ")[1].trim();
                Object[] rowData = {regNo, brand, model, color, status, dom, condition, cc};
                dtm2.addRow(rowData);

                Bike bike = new Bike(regNo, brand, model, color, status, dom, condition, cc);
                vl2.add(bike);
            }
        } catch (IOException e) {
            System.out.println("" + e);
        }
    }

    private void saveTableDataToTextFile() throws IOException {
        String filePath = "carData.txt";
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            for (int row = 0; row < dtm.getRowCount(); row++) {
                String regNo = dtm.getValueAt(row, 0).toString();
                String brand = dtm.getValueAt(row, 1).toString();
                String model = dtm.getValueAt(row, 2).toString();
                String color = dtm.getValueAt(row, 3).toString();
                String status = dtm.getValueAt(row, 4).toString();
                String dom = dtm.getValueAt(row, 5).toString();
                String condition = dtm.getValueAt(row, 6).toString();

                String line = String.format("Reg No: " + regNo + ",, " + "Brand: " + brand + ",, " + 
                        "Model: " + model + ",, " + "Color: " + color + ",, " + "Status: " + status + ",, " + "Dom: " + dom + ",, " + "Condition: " + condition);
                writer.write(line);
                writer.newLine();
            }
        }
    }
    private void saveTableDataToTextFile1() throws IOException {
        String filePath = "bikeData.txt";
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            for (int row = 0; row < dtm2.getRowCount(); row++) {
                String regNo = dtm2.getValueAt(row, 0).toString();
                String brand = dtm2.getValueAt(row, 1).toString();
                String model = dtm2.getValueAt(row, 2).toString();
                String color = dtm2.getValueAt(row, 3).toString();
                String status = dtm2.getValueAt(row, 4).toString();
                String dom = dtm2.getValueAt(row, 5).toString();
                String condition = dtm2.getValueAt(row, 6).toString();
                String cc = dtm2.getValueAt(row, 7).toString();
                String line = String.format("Reg No: " + regNo + ",, " + "Brand: " + brand + ",, " + 
                        "Model: " + model + ",, " + "Color: " + color + ",, " + "Status: " + status + ",, " + "Dom: " + dom + ",, " + "Condition: " + condition+",, "+"CC: "+cc);
                writer.write(line);
                writer.newLine();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarDataTable;
    private javax.swing.JTable CarDataTable1;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton bikeButton;
    private javax.swing.JTextField brandBox;
    private javax.swing.JTextField brandBox1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton carbutton;
    private javax.swing.JTextField ccBox;
    private javax.swing.JTextField colorBox;
    private javax.swing.JTextField colorBox1;
    private javax.swing.JComboBox<String> conditionBox;
    private javax.swing.JComboBox<String> conditionBox1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteButton1;
    private com.toedter.calendar.JDateChooser domBox;
    private com.toedter.calendar.JDateChooser domBox1;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JButton homebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField modelBox;
    private javax.swing.JTextField modelBox1;
    private javax.swing.JTextField regNoBox;
    private javax.swing.JTextField regNoBox1;
    private javax.swing.JRadioButton status1;
    private javax.swing.JRadioButton status2;
    private javax.swing.JRadioButton status3;
    private javax.swing.JRadioButton status4;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateButton1;
    // End of variables declaration//GEN-END:variables
}
